ARG BASE_IMAGE=miko453/headless:lite-novnc
FROM ${BASE_IMAGE}

COPY scripts/entrypoints/start-vnc-rdp.sh /app/start-vnc-rdp.sh

RUN chmod +x /app/start-vnc-rdp.sh && \
    /usr/local/bin/apt.sh switch && \
    apt-get install -y --no-install-recommends xrdp xorgxrdp && \
    /usr/local/bin/apt.sh restore && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 22 5901 10081 3389
CMD ["/app/start-vnc-rdp.sh"]
