ARG BASE_IMAGE=miko453/headless:lite
FROM ${BASE_IMAGE}

RUN /usr/local/bin/apt.sh switch && \
    apt-get install -y --no-install-recommends kali-desktop-xfce xfce4-screenshooter && \
    apt-get purge -y xfce4 || true && \
    /usr/local/bin/apt.sh restore && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["/app/start-vnc.sh"]
