#!/bin/zsh
# 检查并复制 VNC 配置
if [ ! -d "/config/.config/tigervnc" ]; then
    mkdir -p /config/.config/tigervnc
    cp -r /root/.config/tigervnc/* /config/.config/tigervnc/
fi

# 确保权限正确
chown -R qwe:qwe /config/.config/tigervnc
chmod 600 /config/.config/tigervnc/passwd

vncserver :1 -SecurityTypes RA2_256 -localhost no -fg
