ARG BASE_IMAGE=miko453/headless:base-latest
FROM ${BASE_IMAGE}

RUN /usr/local/bin/apt.sh switch && \
    apt-get install -y kali-desktop-xfce && \
    /usr/local/bin/apt.sh restore && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["/app/start-vnc.sh"]
