ARG BASE_IMAGE=miko453/headless:icewm-thin
FROM ${BASE_IMAGE}

COPY scripts/entrypoints/start-novnc.sh /app/start-novnc.sh

RUN chmod +x /app/start-novnc.sh && \
    /usr/local/bin/apt.sh switch && \
    apt-get install -y novnc websockify && \
    /usr/local/bin/apt.sh restore && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 5901 6001
CMD ["/app/start-novnc.sh"]
