ARG BASE_IMAGE=miko453/headless:xfull-latest
FROM ${BASE_IMAGE}

COPY scripts/entrypoints/start-novnc.sh /app/start-novnc.sh
COPY scripts/entrypoints/start-vnc-rdp.sh /app/start-vnc-rdp.sh

RUN chmod +x /app/start-novnc.sh /app/start-vnc-rdp.sh && \
    /usr/local/bin/apt.sh switch && \
    apt-get install -y novnc websockify xrdp xorgxrdp && \
    /usr/local/bin/apt.sh restore && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 5901 6001 3389
CMD ["/app/start-novnc.sh"]
